version: '2'
services:
    nginx:
        image: nginx:1.15.4-alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /etc/nginx/certs
            - /usr/share/nginx/html

    dockergen:
        image: jwilder/docker-gen:0.4.2
        container_name: nginx-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
        container_name: letsencrypt-nginx-proxy-companion
        volumes_from:
            - nginx
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            #- "../volumes/proxy/certs:/etc/nginx/certs:rw"
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

    webasync:
        environment:
            - HTTPS_METHOD=nohttp
            - VIRTUAL_HOST=api.dataunity.org
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=api.dataunity.org
            - LETSENCRYPT_EMAIL=kev@dataunity.org
